services:
  nginx:
    build:
      context: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"

  loki:
    build:
      context: ./loki
    container_name: loki
    ports:
      - "3100:3100"

  promtail:
    build:
      context: ./promtail
    container_name: promtail
    volumes:
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
